/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesDomainIndexRouteImport } from './routes/games/$domain/index'
import { Route as GamesDomainTroubleshootRouteImport } from './routes/games/$domain/troubleshoot'
import { Route as GamesDomainSetupRouteImport } from './routes/games/$domain/setup'
import { Route as GamesDomainModsRouteImport } from './routes/games/$domain/mods'
import { Route as GamesDomainMo2RouteImport } from './routes/games/$domain/mo2'
import { Route as GamesDomainLoadOrderRouteImport } from './routes/games/$domain/load-order'
import { Route as GamesDomainLibraryRouteImport } from './routes/games/$domain/library'
import { Route as GamesDomainCompareRouteImport } from './routes/games/$domain/compare'
import { Route as GamesDomainModsIndexRouteImport } from './routes/games/$domain/mods.index'
import { Route as GamesDomainCollectionsIndexRouteImport } from './routes/games/$domain/collections/index'
import { Route as GamesDomainPreviewModIdRouteImport } from './routes/games/$domain/preview.$modId'
import { Route as GamesDomainModsModIdRouteImport } from './routes/games/$domain/mods/$modId'
import { Route as GamesDomainCollectionsSlugRouteImport } from './routes/games/$domain/collections/$slug'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDomainIndexRoute = GamesDomainIndexRouteImport.update({
  id: '/games/$domain/',
  path: '/games/$domain/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDomainTroubleshootRoute = GamesDomainTroubleshootRouteImport.update({
  id: '/games/$domain/troubleshoot',
  path: '/games/$domain/troubleshoot',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDomainSetupRoute = GamesDomainSetupRouteImport.update({
  id: '/games/$domain/setup',
  path: '/games/$domain/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDomainModsRoute = GamesDomainModsRouteImport.update({
  id: '/games/$domain/mods',
  path: '/games/$domain/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDomainMo2Route = GamesDomainMo2RouteImport.update({
  id: '/games/$domain/mo2',
  path: '/games/$domain/mo2',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDomainLoadOrderRoute = GamesDomainLoadOrderRouteImport.update({
  id: '/games/$domain/load-order',
  path: '/games/$domain/load-order',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDomainLibraryRoute = GamesDomainLibraryRouteImport.update({
  id: '/games/$domain/library',
  path: '/games/$domain/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDomainCompareRoute = GamesDomainCompareRouteImport.update({
  id: '/games/$domain/compare',
  path: '/games/$domain/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDomainModsIndexRoute = GamesDomainModsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesDomainModsRoute,
} as any)
const GamesDomainCollectionsIndexRoute =
  GamesDomainCollectionsIndexRouteImport.update({
    id: '/games/$domain/collections/',
    path: '/games/$domain/collections/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamesDomainPreviewModIdRoute = GamesDomainPreviewModIdRouteImport.update({
  id: '/games/$domain/preview/$modId',
  path: '/games/$domain/preview/$modId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDomainModsModIdRoute = GamesDomainModsModIdRouteImport.update({
  id: '/$modId',
  path: '/$modId',
  getParentRoute: () => GamesDomainModsRoute,
} as any)
const GamesDomainCollectionsSlugRoute =
  GamesDomainCollectionsSlugRouteImport.update({
    id: '/games/$domain/collections/$slug',
    path: '/games/$domain/collections/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/games/': typeof GamesIndexRoute
  '/games/$domain/compare': typeof GamesDomainCompareRoute
  '/games/$domain/library': typeof GamesDomainLibraryRoute
  '/games/$domain/load-order': typeof GamesDomainLoadOrderRoute
  '/games/$domain/mo2': typeof GamesDomainMo2Route
  '/games/$domain/mods': typeof GamesDomainModsRouteWithChildren
  '/games/$domain/setup': typeof GamesDomainSetupRoute
  '/games/$domain/troubleshoot': typeof GamesDomainTroubleshootRoute
  '/games/$domain/': typeof GamesDomainIndexRoute
  '/games/$domain/collections/$slug': typeof GamesDomainCollectionsSlugRoute
  '/games/$domain/mods/$modId': typeof GamesDomainModsModIdRoute
  '/games/$domain/preview/$modId': typeof GamesDomainPreviewModIdRoute
  '/games/$domain/collections/': typeof GamesDomainCollectionsIndexRoute
  '/games/$domain/mods/': typeof GamesDomainModsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/games': typeof GamesIndexRoute
  '/games/$domain/compare': typeof GamesDomainCompareRoute
  '/games/$domain/library': typeof GamesDomainLibraryRoute
  '/games/$domain/load-order': typeof GamesDomainLoadOrderRoute
  '/games/$domain/mo2': typeof GamesDomainMo2Route
  '/games/$domain/setup': typeof GamesDomainSetupRoute
  '/games/$domain/troubleshoot': typeof GamesDomainTroubleshootRoute
  '/games/$domain': typeof GamesDomainIndexRoute
  '/games/$domain/collections/$slug': typeof GamesDomainCollectionsSlugRoute
  '/games/$domain/mods/$modId': typeof GamesDomainModsModIdRoute
  '/games/$domain/preview/$modId': typeof GamesDomainPreviewModIdRoute
  '/games/$domain/collections': typeof GamesDomainCollectionsIndexRoute
  '/games/$domain/mods': typeof GamesDomainModsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/games/': typeof GamesIndexRoute
  '/games/$domain/compare': typeof GamesDomainCompareRoute
  '/games/$domain/library': typeof GamesDomainLibraryRoute
  '/games/$domain/load-order': typeof GamesDomainLoadOrderRoute
  '/games/$domain/mo2': typeof GamesDomainMo2Route
  '/games/$domain/mods': typeof GamesDomainModsRouteWithChildren
  '/games/$domain/setup': typeof GamesDomainSetupRoute
  '/games/$domain/troubleshoot': typeof GamesDomainTroubleshootRoute
  '/games/$domain/': typeof GamesDomainIndexRoute
  '/games/$domain/collections/$slug': typeof GamesDomainCollectionsSlugRoute
  '/games/$domain/mods/$modId': typeof GamesDomainModsModIdRoute
  '/games/$domain/preview/$modId': typeof GamesDomainPreviewModIdRoute
  '/games/$domain/collections/': typeof GamesDomainCollectionsIndexRoute
  '/games/$domain/mods/': typeof GamesDomainModsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/games/'
    | '/games/$domain/compare'
    | '/games/$domain/library'
    | '/games/$domain/load-order'
    | '/games/$domain/mo2'
    | '/games/$domain/mods'
    | '/games/$domain/setup'
    | '/games/$domain/troubleshoot'
    | '/games/$domain/'
    | '/games/$domain/collections/$slug'
    | '/games/$domain/mods/$modId'
    | '/games/$domain/preview/$modId'
    | '/games/$domain/collections/'
    | '/games/$domain/mods/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/games'
    | '/games/$domain/compare'
    | '/games/$domain/library'
    | '/games/$domain/load-order'
    | '/games/$domain/mo2'
    | '/games/$domain/setup'
    | '/games/$domain/troubleshoot'
    | '/games/$domain'
    | '/games/$domain/collections/$slug'
    | '/games/$domain/mods/$modId'
    | '/games/$domain/preview/$modId'
    | '/games/$domain/collections'
    | '/games/$domain/mods'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/settings'
    | '/games/'
    | '/games/$domain/compare'
    | '/games/$domain/library'
    | '/games/$domain/load-order'
    | '/games/$domain/mo2'
    | '/games/$domain/mods'
    | '/games/$domain/setup'
    | '/games/$domain/troubleshoot'
    | '/games/$domain/'
    | '/games/$domain/collections/$slug'
    | '/games/$domain/mods/$modId'
    | '/games/$domain/preview/$modId'
    | '/games/$domain/collections/'
    | '/games/$domain/mods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  GamesIndexRoute: typeof GamesIndexRoute
  GamesDomainCompareRoute: typeof GamesDomainCompareRoute
  GamesDomainLibraryRoute: typeof GamesDomainLibraryRoute
  GamesDomainLoadOrderRoute: typeof GamesDomainLoadOrderRoute
  GamesDomainMo2Route: typeof GamesDomainMo2Route
  GamesDomainModsRoute: typeof GamesDomainModsRouteWithChildren
  GamesDomainSetupRoute: typeof GamesDomainSetupRoute
  GamesDomainTroubleshootRoute: typeof GamesDomainTroubleshootRoute
  GamesDomainIndexRoute: typeof GamesDomainIndexRoute
  GamesDomainCollectionsSlugRoute: typeof GamesDomainCollectionsSlugRoute
  GamesDomainPreviewModIdRoute: typeof GamesDomainPreviewModIdRoute
  GamesDomainCollectionsIndexRoute: typeof GamesDomainCollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$domain/': {
      id: '/games/$domain/'
      path: '/games/$domain'
      fullPath: '/games/$domain/'
      preLoaderRoute: typeof GamesDomainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$domain/troubleshoot': {
      id: '/games/$domain/troubleshoot'
      path: '/games/$domain/troubleshoot'
      fullPath: '/games/$domain/troubleshoot'
      preLoaderRoute: typeof GamesDomainTroubleshootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$domain/setup': {
      id: '/games/$domain/setup'
      path: '/games/$domain/setup'
      fullPath: '/games/$domain/setup'
      preLoaderRoute: typeof GamesDomainSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$domain/mods': {
      id: '/games/$domain/mods'
      path: '/games/$domain/mods'
      fullPath: '/games/$domain/mods'
      preLoaderRoute: typeof GamesDomainModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$domain/mo2': {
      id: '/games/$domain/mo2'
      path: '/games/$domain/mo2'
      fullPath: '/games/$domain/mo2'
      preLoaderRoute: typeof GamesDomainMo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$domain/load-order': {
      id: '/games/$domain/load-order'
      path: '/games/$domain/load-order'
      fullPath: '/games/$domain/load-order'
      preLoaderRoute: typeof GamesDomainLoadOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$domain/library': {
      id: '/games/$domain/library'
      path: '/games/$domain/library'
      fullPath: '/games/$domain/library'
      preLoaderRoute: typeof GamesDomainLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$domain/compare': {
      id: '/games/$domain/compare'
      path: '/games/$domain/compare'
      fullPath: '/games/$domain/compare'
      preLoaderRoute: typeof GamesDomainCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$domain/mods/': {
      id: '/games/$domain/mods/'
      path: '/'
      fullPath: '/games/$domain/mods/'
      preLoaderRoute: typeof GamesDomainModsIndexRouteImport
      parentRoute: typeof GamesDomainModsRoute
    }
    '/games/$domain/collections/': {
      id: '/games/$domain/collections/'
      path: '/games/$domain/collections'
      fullPath: '/games/$domain/collections/'
      preLoaderRoute: typeof GamesDomainCollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$domain/preview/$modId': {
      id: '/games/$domain/preview/$modId'
      path: '/games/$domain/preview/$modId'
      fullPath: '/games/$domain/preview/$modId'
      preLoaderRoute: typeof GamesDomainPreviewModIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$domain/mods/$modId': {
      id: '/games/$domain/mods/$modId'
      path: '/$modId'
      fullPath: '/games/$domain/mods/$modId'
      preLoaderRoute: typeof GamesDomainModsModIdRouteImport
      parentRoute: typeof GamesDomainModsRoute
    }
    '/games/$domain/collections/$slug': {
      id: '/games/$domain/collections/$slug'
      path: '/games/$domain/collections/$slug'
      fullPath: '/games/$domain/collections/$slug'
      preLoaderRoute: typeof GamesDomainCollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GamesDomainModsRouteChildren {
  GamesDomainModsModIdRoute: typeof GamesDomainModsModIdRoute
  GamesDomainModsIndexRoute: typeof GamesDomainModsIndexRoute
}

const GamesDomainModsRouteChildren: GamesDomainModsRouteChildren = {
  GamesDomainModsModIdRoute: GamesDomainModsModIdRoute,
  GamesDomainModsIndexRoute: GamesDomainModsIndexRoute,
}

const GamesDomainModsRouteWithChildren = GamesDomainModsRoute._addFileChildren(
  GamesDomainModsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  GamesIndexRoute: GamesIndexRoute,
  GamesDomainCompareRoute: GamesDomainCompareRoute,
  GamesDomainLibraryRoute: GamesDomainLibraryRoute,
  GamesDomainLoadOrderRoute: GamesDomainLoadOrderRoute,
  GamesDomainMo2Route: GamesDomainMo2Route,
  GamesDomainModsRoute: GamesDomainModsRouteWithChildren,
  GamesDomainSetupRoute: GamesDomainSetupRoute,
  GamesDomainTroubleshootRoute: GamesDomainTroubleshootRoute,
  GamesDomainIndexRoute: GamesDomainIndexRoute,
  GamesDomainCollectionsSlugRoute: GamesDomainCollectionsSlugRoute,
  GamesDomainPreviewModIdRoute: GamesDomainPreviewModIdRoute,
  GamesDomainCollectionsIndexRoute: GamesDomainCollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
